In [8]:
# %load main.py
import os
import torch
import pickle
import networkx as nx
from tqdm import tqdm_notebook

In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [10]:
from GCN import gcn
from trainer import train
#from make_graph import build_graphs
from dataloader import graphs_dict_dataloader
from preprocess import load_and_preprocess
from load_graph_params import load_graph_params

In [11]:
df = load_and_preprocess()

In [12]:
num_adj = 3
num_output_classes = 2
embedding_dim = 1024
num_epochs = 1

In [13]:
weights_dict, word_embeddings, node_param, word_to_idx, weights_tuple_to_idx = load_graph_params()

In [ ]:
graphs_dataset = graphs_dict_dataloader(df, num_adj, word_embeddings)

# trainloader = DataLoader(dataset = graphs_dataset, batch_size = 5)

# for x, y in trainloader:
#     print(x)
#     break

graphs_dataset[8]

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print('Using device - {}'.format(device))

model = gcn(num_output_classes, embedding_dim, node_param, weights_dict, word_embeddings)
loss_function = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.0001, weight_decay=0.0001)

# +
#REINIT GRAPH WEIGHTS
# -

model, graphs = train(trainloader, df, model, loss_function, optimizer, num_epochs, weights_dict, word_embeddings, node_param, word_to_idx, weights_tuple_to_idx)

model



model.eval()

for i in tqdm_notebook(range(1000, 1100)):    
    graphs = get_message_and_update(i, graphs, word_embeddings, node_param, word_to_idx, weights_tuple_to_idx)
    with torch.no_grad():
        activated_out = model(graphs[i])
        print(activated_out)

activated_out

j = 0
for i in model.parameters():
    j+=1

len(weights_dict)

j

len(model.parameters())

In [2]:
from load_graph_params import load_graph_params

In [3]:
weights_dict, word_embeddings, node_param, word_to_idx, weights_tuple_to_idx = load_graph_params()

In [7]:
weights_dict

{'0': Parameter containing:
 tensor([1.5820], requires_grad=True), '1': Parameter containing:
 tensor([-0.5418], requires_grad=True), '2': Parameter containing:
 tensor([-0.6761], requires_grad=True), '3': Parameter containing:
 tensor([0.4269], requires_grad=True), '4': Parameter containing:
 tensor([-0.7086], requires_grad=True), '5': Parameter containing:
 tensor([-0.5324], requires_grad=True), '6': Parameter containing:
 tensor([1.5631], requires_grad=True), '7': Parameter containing:
 tensor([0.5860], requires_grad=True), '8': Parameter containing:
 tensor([-0.1280], requires_grad=True), '9': Parameter containing:
 tensor([1.7572], requires_grad=True), '10': Parameter containing:
 tensor([0.4206], requires_grad=True), '11': Parameter containing:
 tensor([-0.0743], requires_grad=True), '12': Parameter containing:
 tensor([-2.3670], requires_grad=True), '13': Parameter containing:
 tensor([-0.9531], requires_grad=True), '14': Parameter containing:
 tensor([0.8358], requires_grad=Tru

In [6]:
word_to_idx

{'#': '0',
 '$': '1',
 '%': '2',
 "''": '3',
 '+': '4',
 '-': '5',
 '-1': '6',
 '-10': '7',
 '-2': '8',
 '-35': '9',
 '-55': '10',
 '-80': '11',
 '-axis': '12',
 '-ed': '13',
 '-gate': '14',
 '-ide': '15',
 '-ine': '16',
 '-ol': '17',
 '-one': '18',
 '-patric': '19',
 '-philic': '20',
 '-phobic': '21',
 '-ray': '22',
 '-scope': '23',
 '-self-employed/excise-tax': '24',
 '-specific': '25',
 '.-': '26',
 '.a': '27',
 '.arizona': '28',
 '.art': '29',
 '.attacks': '30',
 '.brad': '31',
 '.by': '32',
 '.chemical': '33',
 '.cognitive': '34',
 '.craig': '35',
 '.d': '36',
 '.dan': '37',
 '.encoding': '38',
 '.finally': '39',
 '.flowering': '40',
 '.freud': '41',
 '.high': '42',
 '.http': '43',
 '.if': '44',
 '.in': '45',
 '.instrument': '46',
 '.iraqi': '47',
 '.it': '48',
 '.jack': '49',
 '.john': '50',
 '.jose': '51',
 '.keyssar': '52',
 '.kohlberg': '53',
 '.lawrence': '54',
 '.louis': '55',
 '.many': '56',
 '.miller': '57',
 '.morgan': '58',
 '.multiple': '59',
 '.national': '60',
 '.ober

In [ ]:
weights_dict[weights_tuple_to_idx()]